### ISSUE TITLE
The names "Promise" and "Reflect" in bootstrap.ts are undefined

### ISSUE THREAD

**Issue by somombo** [Urigo/angular2-meteor-auto-bootstrap#11]
Is bootstrap.ts missing an import statements for the Promise type returned by the bootstrap function?

Is it also missing an import statement for the Reflect object/class that is refered to within the defineMetadata function ?

If so where are these supposed to be imported from ?

I am getting error messages to the effect these names are undefined. Please advise.

**Comment by barbatus** [comment]
Promise and Reflect are considered polyfills for Angular2 and should be imported manually by the user or by adding a special package to his app.
Please read here https://github.com/Urigo/angular2-meteor#install-package how to do that.
