### ISSUE TITLE
GetLocation error

### ISSUE THREAD

**Issue by pivie** [Urigo/angular2-meteor-auto-bootstrap#12]
I have a link
&lt;a [routerLink]="['TreesList']"&gt;Trees&lt;/a&gt;
that works when I use
import {bootstrap} from '@angular/platform-browser-dynamic';
but when I switch to 
import {bootstrap} from 'angular2-meteor-auto-bootstrap';
I get the following browser error:
<img width="572" alt="screen shot 2016-05-14 at 7 05 22 am" src="https://cloud.githubusercontent.com/assets/5320893/15268125/84769260-19a2-11e6-8009-74f72db4ebdc.png">
<img width="451" alt="screen shot 2016-05-14 at 7 05 44 am" src="https://cloud.githubusercontent.com/assets/5320893/15268126/84b614b2-19a2-11e6-840e-c0b55e233068.png">

**Comment by dotansimha** [comment]
@pivie Which version of angular, angular2-meteor, angular2-meteor-auto-bootstrap and Meteor do you use?
Also, can you provide a code or repository example? 

Thanks.

**Comment by barbatus** [comment]
obsolete
