### ISSUE TITLE
Type 'Control' is not assignable to type 'typeof Control'.

### ISSUE THREAD

**Issue by AlanForester** [Urigo/angular2-meteor-auto-bootstrap#16]
This code

```
constructor(private router: Router) {
        this.form.email = new Control('', Validators.compose([
            Validators.required,
            ValidationService.emailValidator
        ]));
        this.form.password = new Control('', Validators.required);
        this.authLoginForm = new ControlGroup(this.form);

}
```

gives these errors

> client/imports/auth/login/login.ts (25, 9): Type 'Control' is not assignable to type 'typeof Control'.
> Property 'prototype' is missing in type 'Control'.
> client/imports/auth/login/login.ts (29, 9): Type 'Control' is not assignable to type 'typeof Control'.
> client/imports/auth/login/login.ts (30, 47): Argument of type '{ email: typeof Control; password: typeof Control; }' is not assignable to parameter of type '{ [key: string]: AbstractControl; }'.
> Index signature is missing in type '{ email: typeof Control; password: typeof Control; }'.

**Comment by barbatus** [comment]
so you have these errors, how come you decided it's related to this package?

**Comment by snarun** [comment]
What is this issue? TSC is not able to recognize the assignment. Also, an explicit typecasting is also not fitting. The error is similar to the earlier one. 
*_Type 'AbstractControl' is not assignable to type 'AbstractControl' *_ (from my code)

Found resolution for this. Define the control type as "any" and then assign the control from group.
