### ISSUE TITLE
Issue on Meteor 1.3.4.1

### ISSUE THREAD

**Issue by gooor** [Urigo/angular2-meteor-auto-bootstrap#19]
Having `TypeError: Cannot read property 'NeverChecked' of undefined` on empty project https://www.angular-meteor.com/tutorials/socially/angular2/bootstrapping

**Comment by dotansimha** [comment]
@gooor 
Which version of this package and angular2-meteor do you use? 

Thanks.

**Comment by gooor** [comment]
0.5.6 but I just checked 0.6.0 version and there's no problem.
