### ISSUE TITLE
Cannot read property 'CheckOnce' of undefined

### ISSUE THREAD

**Issue by hongbo-miao** [Urigo/angular2-meteor-auto-bootstrap#20]
After updating angular2-meteor-auto-bootstrap from 0.5.5 to 0.5.6, got this error:

> Cannot read property 'CheckOnce' of undefined

And shows a blank page.

![image](https://cloud.githubusercontent.com/assets/3375461/16673999/8d77d2a2-4481-11e6-848c-e1a452edf7be.png)

**Comment by barbatus** [comment]
make sure you got everything updated right, location of CheckOnce might have changed.
Otherwise I'll need a repo with the issue.

**Comment by Hongbo-Miao** [comment]
sure, I will provide one soon

**Comment by hongbo-miao** [comment]
@barbatus I solved it by updating 

```
"@angular/common": "2.0.0-rc.1",
"@angular/core": "2.0.0-rc.1",
"@angular/platform-browser": "2.0.0-rc.1",
"@angular/platform-browser-dynamic": "2.0.0-rc.1",
```

to

```
"@angular/common": "2.0.0-rc.4",
"@angular/core": "2.0.0-rc.4",
"@angular/platform-browser": "2.0.0-rc.4",
"@angular/platform-browser-dynamic": "2.0.0-rc.4",
```

thanks!
