### ISSUE TITLE
Angular2 RC5 Bootstrap changes

### ISSUE THREAD

**Issue by sdarnell** [Urigo/angular2-meteor-auto-bootstrap#23]
I notice that this package hasn't been updated to match the angular2-meteor package, and presume that with the NgModule changes in RC5 that it may not be needed.

In my app.module.ts file I have added:

```
import { METEOR_PROVIDERS } from 'angular2-meteor';
```

then in the providers property of the NgModule attribute I have added it:

```
@NgModule({
    imports: [BrowserModule, FormsModule, routing],
    declarations: [AppComponent],
    providers: [ appRoutingProviders, METEOR_PROVIDERS ],
    bootstrap: [ AppComponent ],
})
export class AppModule {}
```

Is this the right approach?

**Comment by barbatus** [comment]
yes, it's not needed any more.
