### ISSUE TITLE
Cannot find module 'angular2-meteor-auto-bootstrap'

### ISSUE THREAD

**Issue by thinkrapido** [Urigo/angular2-meteor-auto-bootstrap#6]
=> Client modified -- refreshingclient/app.ts (4, 25): Cannot find module 'angular2-meteor-auto-bootstrap'.
=> Client modified -- refreshing (x2)client/app.ts (4, 25): Cannot find module 'angular2-meteor-auto-bootstrap/bootstrap'.

Your tutorial for angular2 with meteor seem not to be up to date as well.

**Comment by dotansimha** [comment]
Hi @thinkrapido ,
You just see that lint error in the log, or the actual module does not exists and the application fails in the browser? if so, make sure that you run `npm install` after cloning the repo.

**Comment by thinkrapido** [comment]
browser loads correctly the bootstrap but I get an message in the console where meteor runs

**Comment by dotansimha** [comment]
And you set `"moduleResolution": "node"` in your `tsconfig.json`?

**Comment by barbatus** [comment]
seems to be outdated, please re-open if not.

**Comment by enewe101** [comment]
Looks like this is still a problem with the tutorial.  Suggestions here don't work.  Here's hoping devs look into it.  For a minimal example of the error, do the tutorial up to step 3.
